### ISSUE TITLE
npm run scripts do not work on Windows 10

### ISSUE THREAD

**Issue by HAPPYFUNSIGHT** [jimmyangel/howl#13]
```

(anonymous) @ safe-string.js:10
__webpack_require__ @ safe-string.js:10
(anonymous) @ safe-string.js:10
(anonymous) @ safe-string.js:10
__webpack_require__ @ safe-string.js:10
(anonymous) @ safe-string.js:10
__webpack_require__ @ safe-string.js:10
(anonymous) @ safe-string.js:10
(anonymous) @ safe-string.js:10
DevTools failed to load SourceMap: Could not load content for chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/sourcemaps/onloadwff.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
localhost/:1 Refused to apply style from 'http://localhost:8080/lib/Cesium/Widgets/widgets.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
DevTools failed to load SourceMap: Could not load content for http://localhost:8080/bootstrap-theme.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

**Comment by jimmyangel** [comment]
Cannot reproduce. Did you npm install first?

**Comment by HAPPYFUNSIGHT** [comment]
Yes, I run NPM I first.

Because my environment is **win10**, there are many **linux commands I need to replace with windows commands**. For example, the command of "NPM run clean" to clear, create and copy folders
`"scripts": {
    "clean": "**rimraf dist && md dist && md dist\\lib**",
    "build": "npm run clean && webpack",
    "buildp": "npm run clean && webpack -p",
    "webpack": "webpack",
    "dev": "npm run clean && npm run webpack && webpack-dev-server --hot --inline --open",
    "test": "echo \"Error: no test specified\" && exit 1"
  }`

then
`new CopyWebpackPlugin([
			{
				from: path.resolve(__dirname, 'lib'),
				to: path.resolve(__dirname, 'dist/lib'),
				force: true,
				toType: 'dir',
				ignore: ['.*']
			}
		])`

**Comment by jimmyangel** [comment]
Ah, I see. Feel free to issue a PR when you fix it. Thank you.
