### ISSUE TITLE
Update blog url

### ISSUE THREAD

**Issue by jimmyangel** [jimmyangel/howl#16]

**Comment by marcobarrera** [comment]
The url is http://jimmyangel.github.io/ right?

**Comment by jimmyangel** [comment]
The new address is https://morinricardo.com/

I switched over a while ago, but I forgot to update the link.

**Comment by marcobarrera** [comment]
Would you like me to update it?

**Comment by jimmyangel** [comment]
Thank you for offering, but I already did it. It was really a tiny update. Best regards.
